version: '3'
services:
  mysql:
        image: mysql/mysql-server:8.0
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DATABASE}'
            MYSQL_USER: '${USER}'
            MYSQL_PASSWORD: '${PASSWORD}'
        volumes:
            - './docker/mysql/data:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
            retries: 3
            timeout: 5s

